
services:
  - type: web
    name: tubeclone
    env: node
    plan: free
    buildCommand: npm install && npm run backup
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    disk:
      name: tubeclone-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
